# Generated by Django 5.0.8 on 2026-01-12 11:16

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0003_remove_property_link_property_bathrooms_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission_statement', models.TextField(help_text='Company mission statement')),
                ('vision_statement', models.TextField(help_text='Company vision statement')),
                ('about_text', models.TextField(help_text='About Kifaru Impact Retreat')),
                ('brand_story', models.TextField(help_text='The Kifaru story - Debbie and Olivier')),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('kifaru_meaning', models.TextField(help_text='Why the rhino/Big Five symbolism')),
                ('primary_contact_email', models.EmailField(default='requests@techbedkifaru.be', max_length=254)),
                ('whatsapp_number', models.CharField(blank=True, max_length=20)),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('reference_website', models.URLField(blank=True, default='https://techbedkifaru.be/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company Information',
                'verbose_name_plural': 'Company Information',
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('preferred_language', models.CharField(choices=[('english', 'English'), ('french', 'French'), ('dutch', 'Dutch'), ('swahili', 'Swahili')], default='english', max_length=20)),
                ('interests', models.JSONField(blank=True, default=list, help_text='List of interests')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-subscribed_at'],
            },
        ),
        migrations.CreateModel(
            name='CulturalHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('art', 'Art'), ('design', 'Design'), ('food', 'Food & Beverage'), ('tradition', 'Tradition'), ('experience', 'Experience')], max_length=20)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('order', models.PositiveIntegerField(default=0)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cultural_highlights', to='properties.property')),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('answer', models.TextField()),
                ('category', models.CharField(choices=[('booking', 'Booking'), ('payment', 'Payment'), ('cancellation', 'Cancellation'), ('amenities', 'Amenities'), ('general', 'General')], max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('property', models.ForeignKey(blank=True, help_text='Leave blank for general FAQs', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='properties.property')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['order', 'question'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('coworking', 'Coworking'), ('wellness', 'Wellness'), ('dining', 'Dining'), ('transport', 'Transport'), ('coaching', 'Coaching'), ('events', 'Events'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('available_at', models.ManyToManyField(blank=True, related_name='services', to='properties.property')),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(help_text='e.g., Co-Founder, Concierge, Property Manager', max_length=100)),
                ('bio', models.TextField()),
                ('photo', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('is_featured', models.BooleanField(default=False, help_text='Show on main About page')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_members', to='properties.property')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=200)),
                ('guest_photo', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('content', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(default=5, help_text='Rating out of 5')),
                ('is_approved', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False, help_text='Featured on homepage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='properties.property')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
