# Generated by Django 5.0.8 on 2026-01-13 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyInfo',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='property',
        ),
        migrations.RemoveField(
            model_name='service',
            name='available_at',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='property',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='property',
        ),
        migrations.DeleteModel(
            name='CulturalHighlight',
        ),
        migrations.DeleteModel(
            name='FAQ',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='TeamMember',
        ),
        migrations.DeleteModel(
            name='Testimonial',
        ),
    ]
