# Generated by Django 5.0.8 on 2026-01-12 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country_of_residence',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='is_returning_guest',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(choices=[('english', 'English'), ('french', 'French'), ('dutch', 'Dutch'), ('swahili', 'Swahili')], default='english', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='special_preferences',
            field=models.JSONField(blank=True, default=dict, help_text='Dietary, room preferences, etc.'),
        ),
        migrations.AddField(
            model_name='user',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='WhatsApp Number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('staff', 'Staff'), ('concierge', 'Concierge'), ('property_manager', 'Property Manager'), ('external', 'External Client')], db_index=True, default='external', max_length=20),
        ),
    ]
