# Generated by Django 5.0.8 on 2026-01-13 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_remove_travelpackage_properties_and_more'),
        ('users', '0002_user_country_of_residence_user_is_returning_guest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_properties',
            field=models.ManyToManyField(blank=True, help_text='Properties this staff member is assigned to manage', related_name='assigned_staff', to='properties.property'),
        ),
    ]
