# Generated by Django 5.2.3 on 2025-12-01 10:31

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="background_image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="slug",
            field=models.SlugField(blank=True, max_length=250, unique=True),
        ),
    ]
