# Generated by Django 5.0.8 on 2026-01-12 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_property_background_image_property_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='link',
        ),
        migrations.AddField(
            model_name='property',
            name='bathrooms',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='property',
            name='bedrooms',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='property',
            name='cancellation_days',
            field=models.PositiveIntegerField(default=30, help_text='Free cancellation within X days'),
        ),
        migrations.AddField(
            model_name='property',
            name='check_in_time',
            field=models.TimeField(default='15:00:00', help_text='Check-in time (e.g., 15:00 for 3 PM)'),
        ),
        migrations.AddField(
            model_name='property',
            name='check_out_time',
            field=models.TimeField(default='10:30:00', help_text='Check-out time (e.g., 10:30 for 10:30 AM)'),
        ),
        migrations.AddField(
            model_name='property',
            name='continent',
            field=models.CharField(choices=[('Africa', 'Africa'), ('Europe', 'Europe')], default='Africa', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='max_guests',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='property',
            name='min_nights',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='property',
            name='prepayment_percentage',
            field=models.PositiveIntegerField(default=50, help_text='Prepayment percentage required'),
        ),
        migrations.AddField(
            model_name='property',
            name='property_category',
            field=models.CharField(choices=[('retreat', 'Retreat'), ('coworking', 'Coworking'), ('beachfront', 'Beachfront'), ('urban', 'Urban')], default='retreat', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='square_meters',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='terrace_size',
            field=models.PositiveIntegerField(blank=True, help_text='Terrace size in square meters', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='wifi_password',
            field=models.CharField(blank=True, help_text='Universal WiFi password', max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Base price per night (EUR)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('booked', 'Booked'), ('unavailable', 'Unavailable')], default='available', max_length=20),
        ),
        migrations.CreateModel(
            name='ConciergeService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('transport', 'Transport'), ('chef', 'Private Chef'), ('tour', 'Guided Tour'), ('coaching', 'Coaching'), ('babysitting', 'Babysitting'), ('other', 'Other')], max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in EUR (0 if included)', max_digits=10)),
                ('is_included', models.BooleanField(default=False, help_text='Included in stay price')),
                ('requires_booking', models.BooleanField(default=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concierge_services', to='properties.property')),
            ],
            options={
                'verbose_name_plural': 'Concierge Services',
            },
        ),
        migrations.CreateModel(
            name='PropertyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(help_text='e.g., Friendly Concierge, Host, Butler', max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('whatsapp', models.CharField(blank=True, max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='properties.property')),
            ],
            options={
                'verbose_name_plural': 'Property Contacts',
            },
        ),
        migrations.CreateModel(
            name='PropertyFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_type', models.CharField(choices=[('outdoor', 'Outdoor'), ('indoor', 'Indoor'), ('service', 'Service'), ('unique', 'Unique')], max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='properties.property')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PropertyPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accommodation_type', models.CharField(choices=[('master_bedroom', 'Master Bedroom'), ('single_bedroom', 'Single Bedroom'), ('full_apartment', 'Full Apartment')], max_length=20)),
                ('guest_type', models.CharField(choices=[('international', 'International'), ('local', 'Local')], default='international', max_length=20)),
                ('stay_type', models.CharField(choices=[('short_term', 'Short Term'), ('long_term', 'Long Term'), ('weekly', 'Weekly')], max_length=20)),
                ('min_nights', models.PositiveIntegerField(default=1)),
                ('max_nights', models.PositiveIntegerField(blank=True, null=True)),
                ('price_per_night', models.DecimalField(decimal_places=2, help_text='Price in EUR', max_digits=10)),
                ('weekly_price', models.DecimalField(blank=True, decimal_places=2, help_text='Price for full week (if applicable)', max_digits=10, null=True)),
                ('includes_breakfast', models.BooleanField(default=False)),
                ('includes_fullboard', models.BooleanField(default=False)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_options', to='properties.property')),
            ],
            options={
                'verbose_name_plural': 'Property Pricing Options',
                'ordering': ['property', 'accommodation_type', 'stay_type'],
            },
        ),
        migrations.CreateModel(
            name='TravelPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('description', models.TextField()),
                ('duration_nights', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, help_text='Total package price in EUR', max_digits=10)),
                ('includes', models.JSONField(default=list, help_text='List of inclusions')),
                ('meetings_included', models.BooleanField(default=False)),
                ('coaching_available', models.BooleanField(default=False)),
                ('transport_included', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('properties', models.ManyToManyField(related_name='packages', to='properties.property')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel_time_minutes', models.PositiveIntegerField(help_text='Travel time between properties in minutes')),
                ('transport_available', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, help_text='How properties are connected')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_from', to='properties.property')),
                ('related_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_to', to='properties.property')),
            ],
            options={
                'unique_together': {('property', 'related_property')},
            },
        ),
    ]
