# Generated by Django 5.0.8 on 2026-01-13 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_remove_property_link_property_bathrooms_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='continent',
        ),
        migrations.RemoveField(
            model_name='property',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='property',
            name='long_description',
        ),
        migrations.RemoveField(
            model_name='property',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='property',
            name='status',
        ),
        migrations.RemoveField(
            model_name='propertycontact',
            name='is_primary',
        ),
        migrations.RemoveField(
            model_name='travelpackage',
            name='coaching_available',
        ),
        migrations.RemoveField(
            model_name='travelpackage',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='travelpackage',
            name='meetings_included',
        ),
        migrations.RemoveField(
            model_name='travelpackage',
            name='transport_included',
        ),
    ]
