# Generated by Django 5.0.8 on 2026-01-13 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_remove_property_continent_remove_property_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelpackage',
            name='properties',
        ),
        migrations.DeleteModel(
            name='ConciergeService',
        ),
        migrations.DeleteModel(
            name='TravelPackage',
        ),
    ]
