# Generated by Django 4.2.9 on 2026-01-20 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_remove_travelpackage_properties_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertypricing',
            name='number_of_guests',
            field=models.PositiveIntegerField(blank=True, help_text='Number of guests (if pricing varies by occupancy)', null=True),
        ),
    ]
