# Generated by Django 4.2.9 on 2026-01-23 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_propertypricing_number_of_guests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='max_guests',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propertypricing',
            name='accommodation_type',
            field=models.CharField(choices=[('master_bedroom', 'Master Bedroom'), ('full_apartment', 'Full Apartment')], max_length=20),
        ),
    ]
