# Generated by Django 4.2.9 on 2026-02-01 09:45

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_remove_amenity_icon_amenity_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='avatar',
            field=cloudinary.models.CloudinaryField(blank=True, help_text="Reviewer's avatar image", max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='review',
            name='country',
            field=models.CharField(blank=True, help_text="Reviewer's country", max_length=100),
        ),
    ]
