# Generated by Django 4.2.9 on 2026-02-01 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_review_avatar_review_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='reviewer_name',
            field=models.CharField(default='', help_text='Display name for the reviewer', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='avatar',
            field=models.URLField(blank=True, help_text="Reviewer's avatar URL", max_length=500),
        ),
    ]
