# Generated by Django 4.2.9 on 2026-02-01 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_review_reviewer_name_alter_review_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertyimage',
            options={'ordering': ['category', 'order']},
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='category',
            field=models.CharField(choices=[('bedroom', 'Bedroom'), ('kitchen', 'Kitchen'), ('living_room', 'Living Room'), ('garden', 'Garden'), ('outdoor', 'Outdoor'), ('bathroom', 'Bathroom'), ('other', 'Other')], default='other', help_text='Image category/room type', max_length=20),
        ),
    ]
