# Generated by Django 4.2.9 on 2026-02-01 11:47

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0011_alter_propertyimage_options_propertyimage_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('title', models.CharField(blank=True, help_text='Optional caption for the image', max_length=200)),
                ('category', models.CharField(choices=[('property_showcase', 'Property Showcase'), ('lifestyle', 'Lifestyle'), ('amenities', 'Amenities'), ('location', 'Location'), ('events', 'Events'), ('dining', 'Dining'), ('activities', 'Activities'), ('other', 'Other')], default='other', max_length=30)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('is_featured', models.BooleanField(default=False, help_text='Highlight this image')),
                ('is_active', models.BooleanField(default=True, help_text='Show in gallery')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Gallery Images',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
