# Generated by Django 5.0.8 on 2026-02-10 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0012_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertypricing',
            name='guest_type',
            field=models.CharField(choices=[('international', 'International'), ('local', 'Local'), ('all', 'All Guests')], default='international', max_length=20),
        ),
    ]
