# Generated by Django 5.0.8 on 2026-02-10 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0013_alter_propertypricing_guest_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
    ]
