# Generated by Django 5.0.8 on 2026-02-11 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0014_remove_review_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertypricing',
            name='price_per_night',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price in EUR', max_digits=10, null=True),
        ),
    ]
