# Generated by Django 5.0.8 on 2026-02-16 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0015_alter_propertypricing_price_per_night'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='location_description',
            field=models.TextField(blank=True, help_text='Detailed description of the location and surroundings'),
        ),
        migrations.AddField(
            model_name='property',
            name='tagline',
            field=models.CharField(blank=True, help_text='Short catchy description for marketing', max_length=200),
        ),
    ]
