# Generated by Django 5.0.8 on 2026-02-16 13:45

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0016_property_location_description_property_tagline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amenity',
            name='image',
        ),
        migrations.RemoveField(
            model_name='amenity',
            name='label',
        ),
        migrations.RemoveField(
            model_name='highlight',
            name='text',
        ),
        migrations.AddField(
            model_name='amenity',
            name='category',
            field=models.CharField(choices=[('kitchen', 'Kitchen'), ('sanitary', 'Sanitary'), ('bedroom', 'Bedroom'), ('extras', 'Extras')], default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='amenity',
            name='icon',
            field=models.CharField(blank=True, help_text='Icon name or path', max_length=100),
        ),
        migrations.AddField(
            model_name='amenity',
            name='title',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='highlight',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='highlight',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
