# Generated by Django 5.0.8 on 2026-04-12 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0017_remove_amenity_image_remove_amenity_label_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyimage',
            name='category',
            field=models.CharField(default='other', help_text='Image category/room type', max_length=20),
        ),
    ]
