# Generated by Django 5.0.8 on 2026-01-12 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='notes',
        ),
        migrations.AddField(
            model_name='booking',
            name='accommodation_type',
            field=models.CharField(choices=[('master_bedroom', 'Master Bedroom'), ('single_bedroom', 'Single Bedroom'), ('full_apartment', 'Full Apartment')], default='full_apartment', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='cancellation_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='dog_included',
            field=models.BooleanField(default=False, help_text='Small dog (up to 15kg) - only for Ocean Kifaru North-Sea'),
        ),
        migrations.AddField(
            model_name='booking',
            name='guest_type',
            field=models.CharField(choices=[('international', 'International'), ('local', 'Local')], default='international', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='includes_breakfast',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='includes_fullboard',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='jacuzzi_reservation',
            field=models.BooleanField(default=False, help_text='Additional jacuzzi reservation fee'),
        ),
        migrations.AddField(
            model_name='booking',
            name='number_of_adults',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='booking',
            name='number_of_children',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='special_requests',
            field=models.TextField(blank=True, null=True),
        ),
    ]
