# Generated by Django 5.0.8 on 2026-01-13 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_remove_booking_notes_booking_accommodation_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='cancellation_reason',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='cancelled_at',
        ),
    ]
