# Generated by Django 4.2.9 on 2026-01-23 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_propertypricing_number_of_guests'),
        ('booking', '0003_remove_booking_cancellation_reason_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='guests',
        ),
        migrations.AddField(
            model_name='booking',
            name='number_of_guests',
            field=models.PositiveIntegerField(default=2, help_text='Total number of guests'),
        ),
        migrations.AddField(
            model_name='booking',
            name='selected_pricing',
            field=models.ForeignKey(blank=True, help_text='Selected pricing option', null=True, on_delete=django.db.models.deletion.PROTECT, to='properties.propertypricing'),
        ),
        migrations.AddField(
            model_name='booking',
            name='stay_type',
            field=models.CharField(choices=[('short_term', 'Short Term'), ('long_term', 'Long Term'), ('weekly', 'Weekly')], default='short_term', max_length=20),
        ),
    ]
