# Generated by Django 4.2.9 on 2026-01-30 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_remove_amenity_icon_amenity_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0004_remove_booking_guests_booking_number_of_guests_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='accommodation_type',
            field=models.CharField(choices=[('master_bedroom', 'Master Bedroom'), ('full_apartment', 'Full Apartment')], default='full_apartment', max_length=20),
        ),
        migrations.CreateModel(
            name='BlockedDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.CharField(help_text='Reason for blocking (e.g., Maintenance, Renovation)', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_dates', to='properties.property')),
            ],
            options={
                'verbose_name': 'Blocked Date',
                'verbose_name_plural': 'Blocked Dates',
                'ordering': ['start_date'],
            },
        ),
    ]
