# Generated by Django 4.2.9 on 2026-02-02 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_booking_accommodation_type_blockeddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='id_passport_number',
            field=models.CharField(blank=True, help_text='ID or Passport number for verification', max_length=50),
        ),
    ]
