# Generated by Django 5.0.8 on 2026-01-12 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='bank_transfer_reference',
            field=models.CharField(blank=True, help_text='IBAN transfer reference', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='prepayment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Initial prepayment (usually 50%)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='remaining_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Remaining balance', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='EUR', max_length=3),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Card'), ('bank_transfer', 'Bank Transfer'), ('mpesa', 'M-Pesa'), ('paypal', 'PayPal')], max_length=20),
        ),
    ]
