# Generated by Django 5.0.8 on 2026-02-04 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_payment_bank_transfer_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='authorization_url',
            field=models.URLField(blank=True, help_text='Paystack payment URL', null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='paystack_access_code',
            field=models.CharField(blank=True, help_text='Paystack access code', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='paystack_reference',
            field=models.CharField(blank=True, help_text='Paystack transaction reference', max_length=100, null=True, unique=True),
        ),
    ]
